name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic mvg-info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "prepare ant"
        run:  |
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.maven_repository=$HOME/.m2/repository
          EOF

      - name: "(re)generate some files"
        run:  |
          . <(java -jar ~/buildtools.jar)
          generateAll
          correctEols
          correctHeaders header

      - name: "push changes back to github"
        run:  |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub

      - name: "download dependencies (as mentioned in pom)"
        run:  |
          . <(java -jar ~/buildtools.jar)
          getAllDependencies "${{secrets.SCALEWAY_ACCESS_KEY}}" "${{secrets.SCALEWAY_SECRET_KEY}}"
          installJunitlauncher

      - name: "build"
        run:  ant

      - name: "test"
        run:  |
          if ! ant test; then
            for i in TEST-*.xml; do
              echo "=============== $i"
              sed "s/^/>> /" $i
            done
            exit 42
          fi

      - name: "generate javadoc"
        run:  ant javadoc

      - name: "publish action-artifact jar"
        uses: actions/upload-artifact@v1
        with:
          name: sync-proxy.jar
          path: out/artifacts/sync-proxy.jar

      - name: "publish action-artifact sources"
        uses: actions/upload-artifact@v1
        with:
          name: sync-proxy-sources.jar
          path: out/artifacts/sync-proxy-sources.jar

      - name: "publish action-artifact javadoc"
        uses: actions/upload-artifact@v1
        with:
          name: sync-proxy-javadoc.jar
          path: out/artifacts/sync-proxy-javadoc.jar

      - name: "publish action-artifact test-results"
        uses: actions/upload-artifact@v1
        with:
          name: sync-proxy-testresults.jar
          path: out/artifacts/sync-proxy-testresults.jar

      - name: "if NOT master: saving snapshots for other projects on this branch"
        if: github.ref != 'refs/heads/master'
        run: |
          . <(java -jar ~/buildtools.jar)
          storeMyBranchSnapshots

      - name: "if master: tag with version"
        if: github.ref == 'refs/heads/master'
        run: |
          . <(java -jar ~/buildtools.jar)
          setVersionTag

      - name: "if master: publish maven-artifacts (jar/pom/sources/javadoc)"
        uses: ModelingValueGroup/upload-maven-package-action@master
        if  : github.ref == 'refs/heads/master'
        with:
          file : "out/artifacts/sync-proxy.jar"
